### ISSUE TITLE
Useless link on the login page?

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#10]
Not sure why there is a link "Login" (here, in French, "Connexion") on the top-right corner of the login page, that points to the same page anyway?

![capture3](https://user-images.githubusercontent.com/23653367/35111783-59b1e4e4-fc7c-11e7-9225-3e1ba0ea433c.PNG)

**Comment by avvertix** [comment]
> Not sure why there is a link "Login" on the top-right corner of the login page, 

Me too. We are open to accept pull request for removal

**Comment by shenriod** [comment]
Should I make this pull request?

**Comment by avvertix** [comment]
if you want yes, I can assist you in the process

**Comment by shenriod** [comment]
First I'll have to find the correct file :)

Also, should I fork the master for this?

**Comment by avvertix** [comment]
> Also, should I fork the master for this?

yes you should start from master by [synching your fork](https://help.github.com/articles/syncing-a-fork/) ([another guide can be found here](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)) with the latest changes. Then you create a local branch in your fork.

> First I'll have to find the correct file :)

I can tell you that is in the [header.blade.php](https://github.com/k-box/k-box/blob/master/resources/views/headers/header.blade.php#L18-L60). [Blade is the template engine](https://laravel.com/docs/5.4/blade)

**Comment by avvertix** [comment]
Not yet closed, pull request #12 is still open, the issue will be closed when the pull request will be merged
