### ISSUE TITLE
Filetypes in the filter

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#11]
I have (mistakenly) uploaded a link (extension .lnk). It is "recognized" by the filters as a "shp" (which, in general, is a GIS type of file).

I recognize that this is a very borderline case but it might confuse users

![capture4](https://user-images.githubusercontent.com/23653367/35112263-ce15f22a-fc7d-11e7-8a64-42d917c3b913.PNG)

**Comment by avvertix** [comment]
Nice catch. It will be interesting to know also the mime type that was recognized. As a fast way to obtain that information you can simply put the mouse over on the filter and see the URL it points to (or select it and check the URL) as, at the end of it, the mime type will be presented like 

```
http://localhost/documents?properties.mime_type=video/mpeg
```

**Comment by avvertix** [comment]
In K-Box 0.23 the file recognition system was entirely overhauled. By default unrecognized files are now considered binary file with `bin` extensions. Plugins can now define new extension and mime types.
