### ISSUE TITLE
Pagination of projects

### ISSUE THREAD

**Issue by xamanu** [k-box/k-box#138]
### Short Description of the issue

On the project overview only 12 projects are displayed. In case there are more, they are just not listed.

### Expected behavior

A pagination to get to all projects.

### Steps to reproduce the incorrect behavior

Create 13 projects and go to `/documents/projects` and count them.

**Comment by marjanovicsteva** [comment]
Need help with this one? I can do it :smile:

**Comment by avvertix** [comment]
We weren't able to replicate this issue again on latest builds. Closing it

**Comment by shenriod** [comment]
Are you sure? I just replicated it on 0.25.2

See:
15 projects I have access to:
![anmerkung 2019-02-19 144849](https://user-images.githubusercontent.com/23653367/53005677-86cda780-3455-11e9-8989-2156c7ffd68b.png)

But only 12 displayed on /documents/projects
![anmerkung 2019-02-19 145017](https://user-images.githubusercontent.com/23653367/53005786-be3c5400-3455-11e9-968d-1cb509e2d4b0.png)

**Comment by avvertix** [comment]
The list in the projects page is not the same as on the sidebar if you are an admin. The sidebar includes projects that you can access because of the admin role, while the projects page exclusively list projects you are managing or an explicit member.

I understand that this can lead to the confusion that a pagination is missing, but the main issue is that the two lists of projects are not identical

**Comment by shenriod** [comment]
Ok, I understand. Is there a background reason why those lists are different? If not, I would suggest to harmonize them, so that we see exactly the same list on both sides.

**Comment by avvertix** [comment]
The historical reason is related to admin accounts and their super-powers. For accounts without administration ability the list are identical.

**Comment by shenriod** [comment]
Will then this behavior change with the re-design of the rights and permissions https://github.com/k-box/k-box/issues/206 ?

**Comment by avvertix** [comment]
Probably not immediately
