### ISSUE TITLE
Link to the full text of the license in a new window

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#19]
The info panel of the document shows the link to the full text of the license:

![capture](https://user-images.githubusercontent.com/23653367/35730108-a8b59588-0832-11e8-90fd-cde5c107a588.PNG)

The link opens in the same page / tab, which is confusing, It should either be a pop-up, a panel on the current page or (simplier?) in a new window / tab

**Comment by avvertix** [comment]
I think it can be opened in a separate tab

**Comment by shenriod** [comment]
PS: same behavior in the preview window of the document:

![capture](https://user-images.githubusercontent.com/23653367/35856699-978854d4-0b58-11e8-80d1-5239ae6d1eed.PNG)

**Comment by avvertix** [comment]
It is going to be tackled, all links will open in a new browser tab

**Comment by avvertix** [comment]
#25 included the change to let links being opened in a separate browser tab/window
