### ISSUE TITLE
Document does not appear in search results if not in a collection

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#205]
### Short Description of the issue

When a document is not in collection, it does not appear in the search results, even though I can access the doc.

### Expected behavior

If I have access to a document (because it is mine or because it is in a collection I have access to or because someone shared it with me or because it is public or because the link is public), I would expect to be able to search and find it

### Steps to reproduce the incorrect behavior

1. User A uploads a document in his own space (not in a collection)

2. User A sets the sharing options to "Anyone with the link can access"

3. User B gets the link and clicks on it. All is good

4. User B forgets about the link but remembers that the document is called "something something"

5. User B searches "something something"

6. The doc is not returned in the search results

### General information

Version of your K-Box: 0.25.1

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Hi @shenriod, according to steps you shared seems that the expectation is on shared documents with links. Links are just a way to share the document with external users, that are not required to have an account. On this side there is no way to identify a user a present a search experience to who receive multiple links.

If the user is an actual user of the K-Box and it does not have access to the original document is better to share it directly and not use a link. In this way the user will receive a notification and the document will be searchable from the "Shared with me" section.
