### ISSUE TITLE
Change the hierarchy of user roles

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#206]
### Short Description of the issue

To further define what are the user roles of the K-Box and their distinctive sign, we would like to simplify the predefined roles

currently the roles can be summarized as follows

```
guest  <--- partner <--- Project Manager, K-Linker <--- admin
```
where the arrow `<---` means the right side inherits the permission of the left side, plus some capabilities

The K-Linker role was initially thought to let organizations manage better who can publish on the K-Link, but as it turns out is equally powerful as a Project Manager. Considering that users who can publish might not be entitled to manage projects, we would like to change the location of the K-Linker role in the chain

```
guest  <--- partner <--- K-Linker <--- Project Manager <--- admin
```

In this way there is a clear distinction between each role

**Comment by avvertix** [comment]
@shenriod giving your experience with the platform, would you consider this a positive change or a problem?

**Comment by shenriod** [comment]
@avvertix in general I highly welcome a consolidation of the roles. But could we first look at a finer level? What exact rights / actions would now be granted to each role?

**Comment by shenriod** [comment]
Here a suggestion (in **bold** my suggested changes)

Permission | Minimal role
-------------|---------------
User can access the Shared with me section | Guest (see question below)
User can access the Documents page | **Guest** (see question below)
User can upload documents | Partner
User can trash documents | Partner
User can add/remove personal collections | Partner
User may directly share personal documents with other K-Box users | Partner
User can access the Projects section | Partner
User can edit documents | Partner
User can un-/publish documents | **K-Linker**
User can import documents from folders or external URL | **function no longer existing?? remove the permission?**
User can create/edit groups of users defined at institution level | **is this function at all implemented?**
User can create/edit groups of users defined at personal level | **is this function at all implemented?**
User can clear own Trash | **partner**
User can share documents to groups of users defined at institution level |  **is this at all implemented?**
User can create Projects | **Project manager**
User can access the Administration page |  **Project manager**
User can create/disable other K-Box users |  **Project manager**
User can see the K-Box log files | **Admin**
User can perform the K-Box backups and restore |  **Admin**

Also a general question: do we really need a "guest" role at all? If I want to just share a few documents with an "outsider", I will mostly use a public link. Creating a login / password for someone who is only able to see the docs shared with him / her seems a bit overkill

**Comment by avvertix** [comment]
So far we are doing an internal audit of the permission and the following will be removed because they do not match anymore with existing features

- User can import documents from folders or external URL
- User can create/edit groups of users defined at institution level
- User can create/edit groups of users defined at personal level
- User can share documents to groups of users defined at institution level

I see that you see a change in user creation permission. I agree that currently is a lot of effort to pass through an admin to create accounts, but I disagree that let project managers create users is the solution. We are thinking on a user creation workflow that is more suitable for the possible scenarios

> User can un-/publish documents => K-Linker

On this change we agree to name who has that ability a K-Linker, but so far both K-Linker and Project Manager role have the same capabilities set, and therefore cannot be really distinguished.

The idea was to build the K-Linker role as an extension of Partner and then build the Project Manager role as an extension of the K-Linker role to keep the existing project managers being able to publish and to eventually let others being able to publish.


> Also a general question: do we really need a "guest" role at all? If I want to just share a few documents with an "outsider", I will mostly use a public link. Creating a login / password for someone who is only able to see the docs shared with him / her seems a bit overkill

This came as a question also inside the team. We are tempting to keep it until a migration path could be established as currently that role is being actively used. Probably current Guests should become Partners?

**Comment by shenriod** [comment]
> So far we are doing an internal audit of the permission and the following will be removed because they do not match anymore with existing features

=> completely agree with the 4 proposed removals

> I disagree that let project managers create users is the solution.

=> ok, I can live with that. Let's leave the user creation at the admin level

> This came as a question also inside the team. We are tempting to keep it until a migration path could be established as currently that role is being actively used. Probably current Guests should become Partners?

=> If we are not talking about thousands of guests, maybe the cleanest solution would be to see that with the admins of each K-Box. During the migration, we could see on a one by one basis who needs to be upgraded and who can just be deleted / disabled

**Comment by avvertix** [comment]
> => If we are not talking about thousands of guests,

I didn't really checked, but I also think that are not a big number. Probably is enough to notify the admin before the upgrade that will include the change, so this check can be done

**Comment by avvertix** [comment]
So after an internal discussion we decided to not define an explicit K-Linker role, but rather consider a K-Linker every user that has the capability to publish/unpublish to/from the K-Link. The K-Linker role button will be removed from the user creation page to prevent confusion and unexpected changes of the permissions.

The guest user will be deprecated. This means that new Guest users could not be created, but existing ones will continue to work as before
