### ISSUE TITLE
Impossible to trash a document from the global search results' page

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#207]
### Short Description of the issue

When you try to trash a document from the global search's result page, you get an error message, although you are actually entitled to trash the doc

### Expected behavior

I should be able to trash the doc from the global search results as well

### Steps to reproduce the incorrect behavior

1. Search for a document using the global search (e.g. https://[my K-Box URL]/documents/projects?visibility=private&s=red+book)
2. In the search results, select it and click on "Trash"
3. Error:
![anmerkung 2019-02-19 104358](https://user-images.githubusercontent.com/23653367/52992682-4b21e600-3433-11e9-8a3f-7dcbded24dbc.png)

4. Go to the collection where the document is stored (e.g. https://[my K-Box URL]/documents/groups/1621?highlight=15470)

5. Trash the document
6. All good
![anmerkung 2019-02-19 104519](https://user-images.githubusercontent.com/23653367/52992739-7a385780-3433-11e9-82ab-17a240e3566c.png)

### General information

Version of your K-Box: 0.25.2

URL of the page where the problem has occured: https://[my K-Box URL]/documents/projects?visibility=private&s=red+book

Type and version of your browser: Firefox

In what language are you using your K-Box? English

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Thanks for reporting it. I was able to replicate the problem.
