### ISSUE TITLE
Button "sharing settings" disappears when you save on the edit page of a document

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#208]
### Short Description of the issue

When you save changes on the edit page of a doc, the button "sharing settings" disappears in some cases. So far haven't been able to identify when the problem occurs and when not

### Expected behavior

The button should not disappear :-)

### Steps to reproduce the incorrect behavior

1. Go to https://[My K-Box URL]/documents/15455/edit . The button is where it should:
![anmerkung 2019-02-19 111015](https://user-images.githubusercontent.com/23653367/52993719-ff713b80-3436-11e9-9ea4-2d4416377a95.png)

2. Make any change and click on "Save"
3. (in some cases) the button disappears:

![anmerkung 2019-02-19 110809](https://user-images.githubusercontent.com/23653367/52993645-bae5a000-3436-11e9-8ddf-c7d582ed75e6.png)

### General information

Version of your K-Box: 0.25.2

URL of the page where the problem has occured: 

Type and version of your browser: Firefox

In what language are you using your K-Box? English

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
From the observations I think is related to the status of the document, as it seems to disappear when the system is updating the search index.

Could you confirm that after a minute from the save, the button reappears

**Comment by shenriod** [comment]
Yes I can confirm. It didn't even take a minute. Twice refreshing was sufficient

**Comment by avvertix** [comment]
Thanks for the fast reply
