### ISSUE TITLE
Impossible to add myself (admin) to a project

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#211]
### Short Description of the issue

(looks to me like a bug. Could be that it is a wished behavior but then I do not really understand the logics)

Even if I am admin on a K-Box, I cannot add myself to a project on the /projects/11/edit page

### Expected behavior

Admins should be able to add anyone to a project, including themselves. 

### Steps to reproduce the incorrect behavior

1. Be admin
2. Go to /projects/xx/edit
3. Check that you are not in the list of project members
4. Try to add yourself to the project
5. You cannot find yourself in the list

### General information

Version of your K-Box: 0.25.3

URL of the page where the problem has occurred: /projects/11/edit

Type and version of your browser: Firefox

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
I'm evaluating the report to understand if it is bug

**Comment by avvertix** [comment]
So this is indeed a bug that is mostly connected to how the list of possible members is constructed
