### ISSUE TITLE
Impossible to see / change my own permissions (admin)

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#212]
### Short Description of the issue

(looks to me like a bug. Could be that it is a wished behavior but then I do not really understand the logics)

Even if I am admin on a K-Box, I cannot change my rights / permissions

### Expected behavior

Admins should be able to change anyone's permissions, including their owns. This can be very useful, e.g. in the case where you are the only admin on the K-Box (e.g. if another admin's account has been suppressed).

I understand however that this can have negative side effects, e.g. if the only admin of the K-Box removes his own admin rights, then no one is left with admin rights to add / remove users, etc.

At minimum I should be able to see my list of rights

### Steps to reproduce the incorrect behavior

1. Be admin
2. Go to /administration/users/138/edit
3. You cannot see / change your permissions

### General information

Version of your K-Box: 0.25.3

URL of the page where the problem has occurred: /projects/11/edit

Type and version of your browser: Firefox

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
> I understand however that this can have negative side effects, e.g. if the only admin of the K-Box removes his own admin rights, then no one is left with admin rights to add / remove users, etc.

As an admin this is prevented as the negative side effects can be more dangerous than creating a new admin account and change the permission of the old admin account from the newly created one

> At minimum I should be able to see my list of rights

This can found in the documentation https://github.com/k-box/k-box/blob/master/docs/administration/permissions.md
