### ISSUE TITLE
Recent documents page missing pagination

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#219]
### Short Description of the issue

- The recent page do not have pagination links at the bottom when there are 50 recent documents, but 12 documents per page is selected

### Expected behavior

- pagination links should be present when there are more documents then the number to show for each page

### General information

Version of your K-Box: 0.25.x

**Comment by shenriod** [comment]
Small addition: the pagination is missing, no matter how many "documents to display" is selected (12, 24 or 50)

![image](https://user-images.githubusercontent.com/23653367/53413281-64a3ce80-39ed-11e9-9112-e3ff193b1235.png)

But it is possible to access the following pages by manually adding `?page=XX` to the URL
