### ISSUE TITLE
Properties of a collection

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#22]
Currently, when I right-click on a collection, the first 2 entries of the contextual menu are "Edit" and "Details"
![capture2](https://user-images.githubusercontent.com/23653367/35731185-83f1995a-0836-11e8-83ef-17cc805fb170.PNG)

However, both have exactly the same effect: they open the window where I can rename the collection. 
![capture](https://user-images.githubusercontent.com/23653367/35731169-6d563fac-0836-11e8-84a3-20444bb56254.PNG)

Either they should be doing something different or we should remove one of them

Note that, at the project level, the behavior is correct.

**Comment by avvertix** [comment]
I would think that the correct behavior should present a panel, like it happens for projects

**Comment by shenriod** [comment]
Exactly. And I would expect to see on the panel the same kind of information that is there in the Project panel, plus some goodies (that could be added to the project panel as well...):

- [ ] Date of creation of the collection
- [ ] Creator of the collection
- [ ] Number of documents (Bonus: how many private, how many with a direct share link, how many public, how many in English, Russian, French, etc.) -- Mega bonus: I can click on "how many private" to display all the private documents of this collection (and same for public, etc.)
- [ ] The top contributor to this collection (the one with the most documents uploaded? or modified?) -- Mega bonus: I can click on "top contributor" to display all the documents uploaded by him / her
- [ ] The last contributor to this collection - with link to the document
- [ ] The last 3 documents uploaded to this collection - with links to the documents
- [ ] The most common type of files in this collection - with link to all documents of this type
- [ ] The number of files per type of license (Mega bonus: I can click on "how many CC-BY-SA" to display all the documents of this collection released under CC-BY-SA)
- [ ] The list of people with access to this collection
- [ ] The direct link to this collection [for the future, when it will be possible to share collections and subsets of files with external users]
- [ ] The possibility to add an avatar to the collection
- [ ] A nice viz of the activity of this collection / project (showing the number of uploaded and accessed files per day over the last 6 months, e.g.)
- [ ] _more ideas to come probably later_

**Comment by avvertix** [comment]
@xamanu here we have a quite interesting amount of ideas generated after seeing a bug.

Some are easy to understand, while some others are interesting in perspective of filter enhancements. Here I'm referring to the "number of private documents", or to the "How many CC-BY-SA"

**Comment by shenriod** [comment]
Probably related to https://github.com/k-box/k-box/issues/46

**Comment by avvertix** [comment]
So out of all the suggestions I would consider realistic to create a panel with

- Date of creation of the collection
- Creator of the collection
- The last 5-10 documents uploaded to this collection - with links to the documents
