### ISSUE TITLE
[Enhancement] Restore URLs / documents ids

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#230]
### Short Description of the issue

Problem that happened today, probably because of a mismanipulation of a user:

1) A document was stored somewhere on the K-Box
2) The link to this document was sent to many people (users and outsiders)
3) The document "disappeared" (probably trashed by mistake, and somehow not restorable (?))
4) The original document is uploaded again, but obviously receives a new id and thus a new URL
5) The original link no longer works, which can be frustrating for people, when they click on the received link and land on a 404 type of page

### Expected behavior

Can we find a clever way to cope with such situation? Could we, e.g., manually assign an id / URL to a document? This would obviously mean that the K-Box checks that the id manually entered is valid (correct format, not yet existing...). In this case, I could thus assign the "old" id to the "new" document, so that the link sent under point 2) becomes valid again.

I assume that this could have side effects that I am overlooking and that the solution might be actually much more complicated. But any solution to the above described issue would be a very nice add-on towards a better persistence of the links and URLs

### Steps to reproduce the incorrect behavior

-

### General information

Version of your K-Box: 0.25.3

URL of the page where the problem has occurred:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Having the ability to change the link to resemble another document could open possible security and information disclosure issues. 

Each document, when shared with link, receives a unique URL. Uploading a new document that is the same as an old one count as a totally new document, therefore it will receive a new public URL. 

Here the main problem was 

> The document "disappeared" (probably trashed by mistake, and somehow not restorable (?))

When a document is trashed, all shares are automatically removed. A possible solution could be to insert an undo for the trashing operation
