### ISSUE TITLE
Open links of the abstract in a new tab

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#237]
### Short Description of the issue

0.26 introduced support for MarkDown in the abstrat of documents, which is very handy! https://github.com/k-box/k-box/pull/232

However, the links open in the same tab / page. Would be good to open them in a new tab.

### Expected behavior

Open links by default in new tab

Similar to this already solved issue: https://github.com/k-box/k-box/issues/19

### General information

Version of your K-Box: 0.26

URL of the page where the problem has occurred:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Thanks for reporting. The behavior is right now to open all links inside the current tab, but we are unsure if internal links (e.g. the one under the same domain) should be treated in a different way, for example internal links to open in the same time and external links to open in a new tab.

**Comment by shenriod** [comment]
My 2 cents would be that all links should open in a new tab, because I would like to keep my K-Box open when I click on the link. But maybe  other users have a different expectation?

The only case I see where links could / should open in the same tab is (maybe) if there is a link to a document or collection located in the same K-Box. But, anyway, I doubt that users will use a lot the MarkDown syntax to link to an internal document / collection. If we want to have links between documents, we probably would need a dedicated function, where the user can interactively browse through the K-Box and pick the document(s) he wants to link. So out of the scope of this particular issue.

**Comment by avvertix** [comment]
Reflecting about it I tend to be on this expectation

- if there is a link to a document or collection located in the same K-Box open in the same tab
- otherwise open in new tab

**Comment by shenriod** [comment]
> if there is a link to a document or collection located in the same K-Box open in the same tab
Ok as a first step. On a long-term perspective, we should however think of a more practical and robust way to link documents and collections (somehow something in this direction: https://github.com/k-box/k-box/issues/103 )   

>  otherwise open in new tab
+1

**Comment by avvertix** [comment]
This is connected to the Markdown parser and its ability to register extensions. Also #56 suffer the same problem. I opened https://github.com/GrahamCampbell/Laravel-Markdown/pull/126 on the Markdown integration we are using to use the latest changes in the extension authoring.

**Comment by avvertix** [comment]
Waiting for the pull request to be accepted on the upstream library.
