### ISSUE TITLE
Browser language preference is not honored

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#28]
### Short Description of the issue

When the browser has a (supported) preferred language, different than English, the K-Box UI is not honoring the request.

### Expected behavior

The browser preferred language is used, especially on the login page.

### Steps to reproduce the incorrect behavior

_the steps focuses on Firefox, as this behavior was observed in Firefox_

1. go to about:preferences#general
2. change the language preference by putting on top Russian, Tajik or another supported language
3. Refresh the K-Box login page

### General information

Version of your K-Box: 0.19.1, 0.20-beta

Type and version of your browser: Firefox 58

In what language are you using your K-Box? French, Russian, Tajik

### Screenshots

![image](https://user-images.githubusercontent.com/5672748/35922154-20992004-0c1d-11e8-8a4a-7f39f0a4e8ac.png)

**Comment by shenriod** [comment]
In addition, it would be nice to be able to override the browser´s language on the login page, by adding a language dropdown.

And the possibility to force the language of the login page with https://my-kbox.net/en , https://my-kbox.net/ru, https://my-kbox.net/fr, etc.

**Comment by avvertix** [comment]
@shenriod the addition of a language selector is out of the scope of this issue. I opened #30 to track it.
