### ISSUE TITLE
[Enhancement] Order the documents / search results

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#29]
### Short Description of the issue

When I look at documents (in a collection or in the search results), I often want to sort them, e.g. to get first the most recently uploaded documents

### Expected behavior

On every page where documents are displayed, I should be able to sort them in different ways (date of upload, date of modification, uploader, last modifier, language, license, name, etc.)

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.18.5

URL of the page where the problem has occured: N/A

Type and version of your browser: N/A

In what language are you using your K-Box? N/A

### Screenshots

N/A

**Comment by avvertix** [comment]
This is becoming of interest. I would trim the scope a bit to

- Sort by create date (both ways newest to oldest and viceversa)
- Sort by update date (both ways newest to oldest and viceversa)
- Name (from A to Z and Z to A)

**Comment by shenriod** [comment]
Question: what will happen if there are several pages of documents in a collection? When I re-order, does it re-order only the docs on the current page or does it re-order all the documents of the collection? And, if the 2nd case is true, what happens if I am currently on page 2, for example? Do I stay on this page?

**Comment by avvertix** [comment]
We didn't talk fully about the behavior, but I guess that changing the order when you will be on a page different than the first to move you back on the first page with the new ordering. The only state that is likely to be preserved is about the search terms and filters applied.

I would pull-in @giacolos or @AlbinaMuzafarova for an opinion on that.

**Comment by AlbinaMuzafarova** [comment]
I would agree with @avvertix. Moving the user back to the first page and adjusting the entire result set according to the selected filter is the typical behavior i've encountered so far.

**Comment by giacolos** [comment]
> Moving the user back to the first page and adjusting the entire result set according to the selected > filter is the typical behavior i've encountered so far.

I also intuitively agree with such expected behavior.
