### ISSUE TITLE
Add variables to store the name of the network in other available languages

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#3]
Here: https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/networks.php#L57

Please add the variables name_fr, name_tg, etc.

________________________

Also, on https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/networks.php#L60

The text must be changed from 

> Give the network a name. It will be used on the UI when publishing documents or collections. With **both** fields empty the "K-Link Public Network" name will be used

to

> Give the network a name. It will be used on the UI when publishing documents or collections. With **[some variable containing the number of available languages for the name]** fields empty the "K-Link Public Network" name will be used

**Comment by avvertix** [comment]
After a profound reflection I think that adding inside the K-Box a way to change the K-Link name for each specific language is not correct. There could be the case that 10 or more languages needs to be added and if in future multiple K-Links will be supported the names to overwrite will be much more. In addition I think that the name of the K-Link can only be given and changed by the creator of the K-Link itself. The creation of the K-Link can be done by third parties and the K-Box administrator should only be responsible for establishing a connection with the specified K-Link and not the naming.

So far I would keep english and russian as they are now, but in a future version both language options will be removed in favor of the automatic retrieval of the K-Link name https://github.com/k-box/k-link/issues/16
