### ISSUE TITLE
[suggestion] Easily accessible language selector

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#30]
In the comment https://github.com/k-box/k-box/issues/28#issuecomment-363998150 @shenriod reported a feature request:

> In addition, it would be nice to be able to override the browser´s language on the login page, by adding a language dropdown.

**Comment by avvertix** [comment]
The K-Box now honors the user preferred language, so I would not add a language selector on the login screen so far. Maybe could be something to include in the navigation when already logged-in as now it is in the profile page of the user and there are no hint that it is there.

**Comment by najiba-f** [comment]
As I understood, The issue is to duplicate/bring the language selection into navigation menu?

**Comment by avvertix** [comment]
Yes, an idea could be adding the language selection on the navigation header, maybe on the right, inside a dropdown or inside the menu that opens when the user avatar is clicked.

**Comment by najiba-f** [comment]
> Yes, an idea could be adding the language selection on the navigation header, maybe on the right, inside a dropdown or inside the menu that opens when the user avatar is clicked.

Thank you for explanation.
