### ISSUE TITLE
Migrate to PHP 7.2 and test on PHP 7.3

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#303]
PHP 7.1 will reach end-of-life on December 1, 2019 (source: https://www.php.net/supported-versions.php). 

Is mandatory to switch to PHP 7.2 has is actively supported and will receive security fixes for another year.

The best would be to start testing the code also on PHP 7.3 to make easier the switch process.

**Comment by hulkur** [comment]
Updated to 7.2, tested on 7.3.
Some tests not passed locally - kml,gpx file type detection and video processing. Something to do with local setup.

**Comment by avvertix** [comment]
Thanks @hulkur for your interest in this issue. Probably is a big one, but I'll try to follow all the changes why you work on the Pull Request.

**Comment by avvertix** [comment]
I created a branch called `upgrade-to-php-72` to target pull requests for this issue. Since the changes are quite big and spans from development to the Docker image build for production I would test more carefully all the edge cases. 

Thanks @hulkur for starting this journey.
