### ISSUE TITLE
Some buttons are now underlined

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#304]
After the change in the handling of the CSS, some buttons have now an underline that was not previously there.

So far the following 3 have been identified:

- Create or add dropdown
- Preview page
- Collections attached to a document (both in details panel and edit page)

![image](https://user-images.githubusercontent.com/5672748/65489759-159f1880-deac-11e9-9b60-183132159839.png)

![image](https://user-images.githubusercontent.com/5672748/65489771-1d5ebd00-deac-11e9-9f4f-920ca66bfa30.png)

![image](https://user-images.githubusercontent.com/5672748/65489789-2780bb80-deac-11e9-895c-25017fe6ebf4.png)

**Comment by joaopjt** [comment]
I can get that one

**Comment by avvertix** [comment]
Cool! Feel free to assign it to you and ask me anything

**Comment by joaopjt** [comment]
That one seens to be fixed already. I've found another css issues that i`m fixing for and only "big" PR. I guess this issue can be closed for now.

**Comment by avvertix** [comment]
Good to know that this is not an issue anymore.

>  I've found another css issues that i`m fixing for and only "big" PR

Make sure to open an issue on the topic if is big. Especially because after the big PR I opened to use tailwindcss I realized that very big PR might be very difficult to test and check
