### ISSUE TITLE
Upload drop hint appear when moving documents already uploaded

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#306]
### Short Description of the issue

Upload hint message appear when moving documents, already uploaded, to a collection on the sidebar.

### Expected behavior

The hint do not appear

### Screenshots

![image](https://user-images.githubusercontent.com/5672748/65491811-12a62700-deb0-11e9-977e-ef64f8b61453.png)

**Comment by joaopjt** [comment]
i can get that one

**Comment by avvertix** [comment]
That's super!

**Comment by avvertix** [comment]
@joaopjt are you having troubles with this issue?

**Comment by joaopjt** [comment]
@avvertix in really, i've forgot to push the commits and assume the pull request. The swarm ambient is not working very well for development, i assume that kubernets would be better for this one (just a observation). I will reopen the project and finish those issues that i've picked up. If you preffer, we can make a call to sync those issues toguether before the PR.

**Comment by avvertix** [comment]
A bit excessive to use swarm, a simple docker compose would have worked. Kubernetes will overly complicate the setup for now and is not a thing we would try soon.

For now just rebase on master (we switched to php 7.2 and did lot of other changes) and open the pull request

**Comment by joaopjt** [comment]
Awesome! Are you using docker-sync for the front-end files? I'm still not getting the updates, even restarting the kbox container... Can you help me with this one?

**Comment by avvertix** [comment]
So my setup is pretty basic. I have PHP 7.2, Node 11 and Yarn installed on my machine (Node 12 has a problem with the old version of [Gulp](https://gulpjs.com/) we are currently using). About the database and the full search text service I use the [docker-compose.dev.yml](https://github.com/k-box/k-box/blob/master/docker-compose.dev.example.yml) included in the repository. 

For always getting the latest css and js I run `yarn watch` which will compile on changes and for serving the pages I use `php artisan serve`, which will create a webserver on port 8000. Of course you need to generate the specific `.env` for connecting your setup to the database. For a longer explanation please refer to [docs/developer/developer-installation.md](https://github.com/k-box/k-box/blob/master/docs/developer/developer-installation.md#k-box-development).

If you want to develop entirely in Docker I would suggest to use a Docker image for php in which you mount as read/write volume the folder with the source and execute all the configuration steps there. For example this docker image `docker.klink.asia/main/docker-php:7.2` contains PHP 7.2, Node 11, Yarn, Composer and the necessary PHP extensions. In this way you can enter the running container and execute yarn watch, composer install, and start the php integrated web server using `php artisan serve` (remember to expose port 8000 from the container.

**Comment by avvertix** [comment]
Are you still having troubles with the setup @joaopjt?

**Comment by joaopjt** [comment]
No. Zero problems until now. I'm just uncertanly about the all sync of docker hard discs with the bundled code from gulp

**Comment by avvertix** [comment]
That depends on how you prefer to organize your development environment. 

In any case feel free to submit also a work in progress pull request
