### ISSUE TITLE
Show only users that match the search when sharing to existing users

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#309]
Focusing on the add users field in the sharing dialog causes all users to be listed.

![image](https://user-images.githubusercontent.com/5672748/65493975-42572e00-deb4-11e9-9e84-ef18781c9ec5.png)

This can work within a team or a small organization, but is not privacy aware and for big organizations this could have a very long list of names and emails.

A possible approach could be:

- do not show by default any users in the list
- let the user type at least 2 or 3 characters of the username and show the users that match the search (show only the username) (e.g. the first 6 or 8 that matches)
- let the user be able to type a full email address and show the username that matches the search

**Comment by joaopjt** [comment]
I can get that one too ;)

**Comment by avvertix** [comment]
Oh Wow! If you want you can take it, Make sure to assign it to yourself so other can see that this has someone working on it
