### ISSUE TITLE
Create a project without adding users

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#32]
### Short Description of the issue

Currently, we need to add at least one user (additionally to the user currently creating the project) in order to be able to create the project.

There might be cases where we want to create a project and its structure of collections without adding users yet.

### Expected behavior

Possible to create a project without adding users

### Steps to reproduce the incorrect behavior

1. Create project

2. Save it without adding a user

3. Error message

### General information

Version of your K-Box: 0.18 - 0.20

URL of the page where the problem has occured: https://test.slmtj.net/projects/create

Type and version of your browser: N/A

In what language are you using your K-Box? N/A

### Screenshots

![capture](https://user-images.githubusercontent.com/23653367/36012112-b15197d2-0d7d-11e8-8acb-f0cf162f954b.PNG)

**Comment by avvertix** [comment]
Seems that the validation rule for the field imposes a required value. I think the implementation should behave correctly also if the required is changed to: must be a valid user if set
