### ISSUE TITLE
Display the collection(s) of a document in the search results

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#33]
### Short Description of the issue

In the search results we do not see to what collection(s) the documents belong (except in the filters). Some GUI magics would be very nice here (e.g. so that we can see the whole tree, from the project to the sub-sub-sub-collection(s) to which the document belongs)

### Expected behavior

A hover on the document  or an additional field shows the whole tree(s) where it is stored. Each project / collection of this tree is clickable

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.18 - 0.20

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

![capture](https://user-images.githubusercontent.com/23653367/36012324-2c3fa550-0d7f-11e8-8875-5c03aa3288b9.PNG)

**Comment by avvertix** [comment]
The information is currently visible in the details panel and will make the UI too much crowded. We are not looking in adding collections in the list view on the short/medium term
