### ISSUE TITLE
[Bug]Buttons on the preview page of documents not clickable on Internet Explorer 11

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#34]
### Short Description of the issue

On the preview page of a document, the button showing the collection and the link to the license are not clickable when using IE 11

### Expected behavior

Should be clickable

### Steps to reproduce the incorrect behavior

1. On the preview page of a document, open the "Details" panel

### General information

Version of your K-Box: 0.18 - 0.20

URL of the page where the problem has occured:

Type and version of your browser: IE 11.0.9600.18893

In what language are you using your K-Box? 

### Screenshots
![capture](https://user-images.githubusercontent.com/23653367/36016963-634e3d00-0d97-11e8-911b-112320f45f7e.PNG)

**Comment by shenriod** [comment]
PS: the button with the name of a collection on the "Edit" page of the document works fine

![capture](https://user-images.githubusercontent.com/23653367/36017039-d7a2d620-0d97-11e8-84f9-eb5f517da595.PNG)

**Comment by avvertix** [comment]
Could you please tell which OS version are you using?

It was not possible to replicate the described behavior on IE11 version 11.248.16299 on Windows 10 (Fall Creators Update, version 1709 with February 2018 security update)

**Comment by avvertix** [comment]
The cause is the same of https://github.com/k-box/k-box/issues/39#issuecomment-367612930

A further investigation confirmed the bug and the fact that only IE11 on Windows 7 is affected
