### ISSUE TITLE
Inconsistencies in the way the roles and permissions are defined

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#36]
### Short Description of the issue

I want to give to my focal points the possibility to create new users, but without necessarily giving them all other admin rights. I thus gave one user the following rights:

- [x] User can see documents that have been shared with him
- [x] The user can access all the private documents of the institution
- [x] The user can upload documents
- [x] The user can delete documents
- [x] The user can manage personal document collections
- [x] User may share personal documents with a single or a "personal" group of users
- [x] The user can manage project collections
- [x] The user can edit documents
- [x] **User can create/edit groups of users defined at institution level**
- [x] **User can create/edit groups of users defined at personal level**
- [x] **The user can access to the DMS administration panel**
- [x] **The user can manage DMS users**

But still the user doesn´t see the Administration button:

![capture](https://user-images.githubusercontent.com/23653367/36026544-65c103a2-0db9-11e8-8c76-c3be31f6fa66.PNG)

If I manually type the URL https://my-k-box.net/administration I then see the full administration panel, although I only wanted the user to be able to manage the users

There are obviously some inconsistencies in the way the roles and permissions are managed and displayed.

### Expected behavior

The list of permissions and their implications should probably be re-designed? 

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.18 - 0.20

URL of the page where the problem has occured: https://my-k-box.net/administration/users/4

Type and version of your browser: Firefox

In what language are you using your K-Box?  English

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
With all the pull requests merged we removed the permissions that do not match anymore to active features
