### ISSUE TITLE
Order of the languages in the dropdown selectors

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#38]
### Short Description of the issue

Currently the list of languages in the drop-down selectors are not alphabetical, but follows a predefined order:

English
Russian
Tajik
French

### Expected behavior

The languages should be written in their own alphabet and then sorted alphabetically. This way, each language will always be "at the same place in the drop-down" (independently from the language of the UI) and each user can easily find his language of choice (a Russian user might not know what "Russian" is and would like to see "русский" in the drop-down)

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 

URL of the page where the problem has occured: 0.18 - 0.20

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

How the dropdowns could / should look like:

![unnamed](https://user-images.githubusercontent.com/23653367/36085075-d109b618-0fe4-11e8-9a78-46ca1a4c91bc.png)

**Comment by avvertix** [comment]
Listing in language switcher was changed in #475 to follow the alphabetical order of the ISO 639-1 language code, which at a first inspection is the same order that Wikipedia applies. In addition the localized labels are presented in their own language.
