### ISSUE TITLE
[Bug]Impossible to logout on IE 11

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#39]
### Short Description of the issue

On IE11 it is impossible to click on "Logout". When you hover on the top-right corner, the logout button appears but when you move your mouse to click it, it disappears too quickly

### Expected behavior

Button should be clickable, as it is with Firefox

### Steps to reproduce the incorrect behavior

1. Hover the icon on the top-right corner

2. The "logout" button appears

3. Move your cursor towards the "logout" button

4. The button disappears before you can click it

### General information

Version of your K-Box: 0.18 - 0.20

URL of the page where the problem has occured: All

Type and version of your browser: Internet Explorer 11

In what language are you using your K-Box?

**Comment by avvertix** [comment]
@shenriod I was not able to reproduce the problem on the K-Box versions you specified, can you please submit an animated GIF showing the behavior. A tool for creating animated GIFs can be [Licecap](https://www.cockos.com/licecap/)

**Comment by avvertix** [comment]
Seems that is a problem that affects only IE11 on Windows 7. If the compatibility mode is used the problem do not arise. A fix will be available soon
