### ISSUE TITLE
Modernize login screen

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#396]
The login screen remained almost unchanged since the initial release. I think that is time to modernize it and think also about personalization.

The next screen shows a potential idea for mobile and desktop. 

![k-box](https://user-images.githubusercontent.com/5672748/87250170-7a3f5a00-c463-11ea-9d4d-d5475e9f6d25.png)

The picture starts to appear on a medium sized screen.

Thinking about personalization I think:

- logo, the K-Box logo could be replaced with the organization logo
- picture, select a picture or use a solid fill
- eventual text overlay on the image

**Comment by shenriod** [comment]
Very good!!!

Another possible improvement (although not only for the login screen): possibility to personalize the color scheme of the K-Box (e.g. to match the look&feel of the organisation using the K-Box)

**Comment by avvertix** [comment]
I made quite some progress in the related pull request, below some screenshots of the current status. The Image come from [Unsplash](https://unsplash.com/photos/xrjDqK1HPWg). Also connected pages for recover password and verify email address are based on the same layout, just without the image. The register page also uses the same layout and image.

Behind the scenes I isolated the K-Box logo and the image in a component in perspective of personalization.


**small screen**

![image](https://user-images.githubusercontent.com/5672748/88965930-ce439e80-d2ab-11ea-8982-982b6e74c3b3.png)


**medium screen**

![image](https://user-images.githubusercontent.com/5672748/88965896-bc61fb80-d2ab-11ea-8a65-be9e0d003646.png)


**large screen**

![image](https://user-images.githubusercontent.com/5672748/88965838-a3594a80-d2ab-11ea-9a4a-89efd0ae1dea.png)
