### ISSUE TITLE
Number of characters for the password

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#4]
How many characters are necessary for a password?

Here
https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/passwords.php#L16

it says 6

while here

https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/passwords.php#L40

and here

https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/profile.php#L30

it says 8

Please harmonise

**Comment by avvertix** [comment]
Thanks for pointing this out. Our plan is to use `8` as the required minim characters.
