### ISSUE TITLE
[enhancement]Identify documents which are "not the same but similar"

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#41]
### Short Description of the issue

We had the following case yesterday:

- User A uploads a document
- User  B uploads "the same document"
- The system doesn't complain and we now have "twice the same document" in the system

After double-checking, we identified that the 2 docs were different from a computer perspective (different size and thus, to some extent, different content) but exactly the same from a user perspective (looking at both documents side by side, you cannot tell the difference).

### Expected behavior

Would it be possible to enhance the system to identify the likelihood that 2 documents are "the same from a user perspective"? Typical example are 2 identical powerpoint presentations where, for one of them, a graphic has been slightly moved or where the name of the author has been changed.

When I upload the 2nd version of the document, the system could say "hey, I found this other document that looks bloody similar to the one you are trying to upload. You might want to check if yours is not just a new version of the same document"

### Steps to reproduce the incorrect behavior

N/A

### General information

N/A

### Screenshots

N/A

**Comment by shenriod** [comment]
Probably loosely related to this: https://klink.uservoice.com/forums/303582-k-link-dms/suggestions/13911630-explicitly-relate-documents-that-have-a-llink-to-e

**Comment by avvertix** [comment]
Could be an interesting option and we might accept pull requests on the topic.

**Comment by avvertix** [comment]
It has been open for quite a long time and we don't have plans for this feature in medium period so this issue will be closed in order to keep the issues backlog up-to-date.
