### ISSUE TITLE
Localization Issue

### ISSUE THREAD

**Issue by najiba-f** [k-box/k-box#418]
### Short Description of the issue
Currently, some part of the interface is not localized. When switching to Russian and Tajik languages, some menu and handle messages are published in English. An example is shown below in the screenshots.

### Screenshots
![lang_issue](https://user-images.githubusercontent.com/10413071/90470041-db79dd80-e133-11ea-8a2f-410717382c01.png)
![lang_issue_1](https://user-images.githubusercontent.com/10413071/90470046-df0d6480-e133-11ea-8e13-28bbb182c103.png)

**Comment by avvertix** [comment]
Hi @najiba-f we accept pull requests for translation improvements. Most of the strings are represented using [Laravel's short key syntax](https://laravel.com/docs/7.x/localization#using-short-keys).

To get an overview of the missing translation keys we implemented the command `php artisan lang:check`. Running it like in the example below will give you the list of keys that are missing from other languages:

```bash
php artisan lang:check --report file.txt
```

Where `file.txt` is the file in which you would save the generated report. More details can be found in the [documentation of the command](https://github.com/k-box/k-box/blob/master/docs/developer/commands/lang-check.md).

**Comment by najiba-f** [comment]
Hi @avvertix. Thank you for instructions.

**Comment by avvertix** [comment]
#446 improves the localization, so this issue can be closed
