### ISSUE TITLE
[Bug]Language of a document wrongly displayed in the document panel and on the preview page

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#42]
### Short Description of the issue

See here:

![capture](https://user-images.githubusercontent.com/23653367/36136235-396f57cc-10b1-11e8-9f82-13f6209ca09b.PNG)

and here:
![capture2](https://user-images.githubusercontent.com/23653367/36136298-820287d4-10b1-11e8-8eda-88a3ac7716e6.PNG)

although:
![capture3](https://user-images.githubusercontent.com/23653367/36136407-1b313338-10b2-11e8-9e58-2458a64340c9.PNG)

The document is public: https://eba.klink.asia/klink/cba519/preview

### Expected behavior

Language should be displayed correctly

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.18

URL of the page where the problem has occured: https://eba.klink.asia/klink/cba519/preview

Type and version of your browser: Firefox 58 and IE11

In what language are you using your K-Box? English

**Comment by avvertix** [comment]
We reflected internally on that, and the outcome was to have a selection of trusted languages each specific K-Box relies on. In this way:

- In case of conflict between trusted and not-trusted languages (like Bulgarian and Tajik in case at hand), it could be resolved by giving to Tajik a higher score;
- In case only not-trusted languages are returned, the detection can keep following the normal pathway
