### ISSUE TITLE
Show more than 12 files on one page

### ISSUE THREAD

**Issue by najiba-f** [k-box/k-box#424]
### Short Description of the issue

Currently, in K-box, the number of the listed document is 12. User can't change the list of documents he wants to see.

### Expected behavior

It would be good if user could select from dropdown list the number of listed documents.

**Comment by avvertix** [comment]
Yes, that would be good. Currently the [recent page has this option](https://github.com/k-box/k-box/blob/52559c0fc11e4e9a41c02468b377a1e00f5a9502/app/Http/Controllers/Document/RecentDocumentsController.php#L41-L43) and the value is persisted in the user's profile. The current values can be seen in the [`recent.blade.php` view file](https://github.com/k-box/k-box/blob/52559c0fc11e4e9a41c02468b377a1e00f5a9502/resources/views/documents/recent.blade.php#L22-L26).

I would keep the limits as 12, 24 and 50 for performance reason.

**Comment by shenriod** [comment]
Very nice to see a (first?) issue fully solved by other developers!! Well done and thank you @najiba-f

**Comment by najiba-f** [comment]
Thank you very much @shenriod :)
