### ISSUE TITLE
[Enhancement]Change the default behaviour of the search engine when no keyword is used

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#43]
### Short Description of the issue

Currently, when I enter several words into the search bar, the search engine assumes that the user means OR:

_pasture Tajikistan_ will return all results that contain _pasture_ OR _Tajikistan_

It seems however that the intuitive behaviour of most users is to expect an AND by default. One concrete example, with this document: https://eba.klink.asia/klink/b10cc1/preview 

When searching the terms _heltberg vulnerability mapping world bank_ 
in the K-Box https://eba.klink.asia/documents/projects?visibility=private&s=heltberg+vulnerability+mapping+world+bank the search results are spread on 110 pages and the wished document does not appear on the first page

When searching the terms _heltberg AND vulnerability AND mapping AND world AND bank_ 
in the K-Box https://eba.klink.asia/documents/projects?visibility=private&s=heltberg+AND+vulnerability+AND+mapping+AND+world+AND+bank the search results are obviously much more pertinent and is probably what most users would be expecting by default

Now, since this document is anyway available online, let's make the same exercise with usual search engines:

DuckDuckGo: https://duckduckgo.com/?q=heltberg+vulnerability+mapping+world+bank&t=hg&ia=web
Google: https://www.google.com.tj/search?q=heltberg+vulnerability+mapping+world+bank&oq=heltberg+vulnerability+mapping+world+bank
Bing: www.bing.com/search?q=heltberg+vulnerability+mapping+world+bank

In all 3 cases, the 1st result is satisfactory, although I didn't use any keyword in the search.

I assume that the K-Box users are therefore used to this behaviour and thus assume that "AND" is implied when no keyword is used.

### Expected behavior

If no keyword is used in a search, the search engine must assume that AND is implied

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.18 - 0.20

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

N/A

**Comment by shenriod** [comment]
NB: I have had since a long time the feeling that the above described behavior is more intuitive and got in the last days / weeks confirmation from several users that this also what they are expecting. So the behaviour of the search engine should be adapted very soon, unless there are **very strong** arguments against it, that I am missing

**Comment by shenriod** [comment]
The version 0.20 should bring some improvements to the search engine, that will not change the default behaviour but that will improve the quality of the results and achieve the expected results.

This issue will be closed after 0.20 has been tested successfully in this regard

**Comment by avvertix** [comment]
To be precise the change is related to https://github.com/k-box/k-search-engine/releases/tag/v0.4.0 and https://github.com/k-box/k-search/releases/tag/v3.2.0-1

**Comment by shenriod** [comment]
Tested and approved in 0.20. We can close
