### ISSUE TITLE
Search documents based on their metadata

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#46]
### Short Description of the issue

Users want sometimes to find "the document that has been uploaded my Natalya last week and that has to do with ICSD". At the moment it is not possible to specifically search for this

### Expected behavior

It should be possible to search by (and to filted the results by // and to order the results by):

- Uploader / last modifier of document
- Date of upload / modification
- Status of the document (public, private, direct link, etc.)
- License type
- etc.

Probably related to https://github.com/k-box/k-box/issues/22

### Steps to reproduce the incorrect behavior
N/A

### General information

Version of your K-Box: 

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
With #29 the current filters can mitigate this scenario, so this will be closed
