### ISSUE TITLE
Provide only one button for file uploads

### ISSUE THREAD

**Issue by avvertix** [k-box/k-box#463]
### Short Description of the issue

The K-Box offered two ways for file upload, one for documents and the other for videos.

![image](https://user-images.githubusercontent.com/5672748/100517262-abf25c80-3189-11eb-9277-4cc1c80f0d45.png)

This generate confusion of when to use one approach or the other. In addition users prefer to drag and drop files, which by default uses the "Document uploader".

### Expected behavior

Considering the usage scenario the expectation is to have a single "Upload file" button that can be used for all kind of files.

**Comment by shenriod** [comment]
I fully support this but I also liked the resumable upload for big files. Will this now disappear or be integrated in the standard upload procedure?

**Comment by avvertix** [comment]
The idea is to integrate both into a seamless workflow, but this will not come immediately

**Comment by avvertix** [comment]
After reflection hiding an option and removing all the current code does not make sense. Instead a proper refactor and evolution must be carefully planned. The change will not take place for now.
