### ISSUE TITLE
Support the option to add free text / comment to projects and collections

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#473]
### Short Description of the issue

It is possible to add abstracts / comments to a document in K-Box. The same functionality would be welcome for collections and projects

### Expected behavior

In the panel of a project or collection, enable the option to add a simple or markdown text

![image](https://user-images.githubusercontent.com/23653367/102923267-c02b3000-448f-11eb-8770-fbb1757a77f1.png)

This could allow users to add simple comments, to link collections to external resources,...

On the long-term, this could evolve to a NextCloud-like functionality of chatting on a document / collection

**Comment by avvertix** [comment]
Projects already support a markdown description. Editing is allowed to the project manager. I agree that for collection this is not possible and we can think if it is necessary.

**Comment by shenriod** [comment]
Ok, sufficient for now I guess, thanks!
