### ISSUE TITLE
Markdown not recognized in projects' description

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#474]
### Short Description of the issue

A project administrator can add free text as a description of a project. This should support markdown but currently the raw text is displayed in a project's "details panel" and not the formatted text

### Expected behavior

_write here what should actually happen_

### Steps to reproduce the incorrect behavior

_1. List_

_2. all the steps_

_3. that have lead to the incorrect behavior_

### General information

Version of your K-Box: 

URL of the page where the problem has occurred:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Hi @shenriod thanks for reporting the bug. Would be awesome if you can help us fixing the issue by submitting a pull request!
