### ISSUE TITLE
Detail panel on the preview page of a public document

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#51]
### Short Description of the issue

When I send a link to the preview page of a document to someone who does not have access to the K-Box, the detail panel is empty:

![capture](https://user-images.githubusercontent.com/23653367/36660740-0b047c56-1afb-11e8-85c1-268031d36002.PNG)

### Expected behavior

The panel should either be disabled or contain relevant information, when someone who is not logged in displays the preview page of a public document

### Steps to reproduce the incorrect behavior

1. Go to the preview page of public document, **without** being logged in in the K-Box

2. Click on "Details"

3. The detail panel is empty

### General information

Version of your K-Box: 0.18

URL of the page where the problem has occured:

Type and version of your browser: Firefox 58

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Sounds as a bug. The details panel should show public information about the document

**Comment by shenriod** [comment]
After discussing with a user, the detail panel of the document should probably show at least:

- Name of the owner / institution
- Link to the "mother resource" (K-Box, website,...) hosting the document
- Date of upload and / or last modification
- Main contact
- License

Full list to be discussed of course

**Comment by avvertix** [comment]
This is categorized as bug, the topic here is that the usual details panel is not presented if the user is not logged in and browsing a public file. The issue aims to fix the part that is not showing the already existing details section

**Comment by avvertix** [comment]
A fix for issue was included in release 0.23 while handling the preview extensions (#131, #133)
