### ISSUE TITLE
[Enhancement] Editting of documents

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#52]
### Short Description of the issue

(an issue that has been discussed many times, so just a placeholder here to not forget it)

A "Google-Doc-like" function for collaborative editting in K-Box would be very nice but is probably not realistic.

However a middle-way could be found to make it easier for users to edit documents stored in a K-Box

### Expected behavior

A middle-way could look like this:
1) The user clicks on "Edit this document"
2) The document is downloaded and opened with the default application 
3) [While the document is open, it is put on read-only mode on the K-Box. Nobody can upload a new version]
4) The user edits the document offline
5) When the user closes the document, it gets uploaded to K-box as a new version of the document
6) The document is put again in write-mode

This is the behaviour that we have in our current corporate DMS (and I had a similar one in a previous job in another company). I am not sure though what it would mean in terms of plugin necessary for the browser or add-on to be installed on the users's system?

### Steps to reproduce the incorrect behavior

N/A

### General information

N/A

### Screenshots
N/A

**Comment by shenriod** [comment]
PS: a mid-size solution here could be to integrate a pad-tool in the K.Box (etherpad, cryptpad,...) to allow at least basic collaborative editing on simple documents. Those pads should then be viewable / searchable like any K-box document

**Comment by avvertix** [comment]
Currently we don't have plans for file editing. We might consider it for the future therefore I'm closing now.
