### ISSUE TITLE
[Enhancement] Increase the time during which a document is highlighted

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#57]
### Short Description of the issue

When clicking on the collection of a document (e.g. on the preview page), the link points to the collection and the document is highlighted in yellow: https://eba.klink.asia/documents/groups/122?**highlight=924**

However, if the document is at the end of the page, the highlight will usually disappear before the user has scrolled down. 

### Expected behavior

Minimum option: increase the duration of the highlighting. Maybe 10 seconds?
Fancy option: keep the highlighting activated for x seconds after it is actually visible to the user (e.g., from the moment where the user has scrolled sufficiently to display the document)

### Steps to reproduce the incorrect behavior

1. Click on the collection name from the Details panel of the preview page of a document

### General information

Version of your K-Box: 0.20

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box?

**Comment by avvertix** [comment]
Hi @shenriod, the problem is not the highlight time, but the fact that the automated scrolling is not happening. Could you please tell me the version of your browser. Thanks

**Comment by shenriod** [comment]
Same behavior with:

Firefox 59.0.3 (64-bit)
Internet Explorer 11.309
Microsoft Edge for Windows 10

**Comment by avvertix** [comment]
This needs to be investigated on the browser side, because appears to be a JavaScript problem. According to https://caniuse.com/#feat=scrollintoview the browsers support the used method

**Comment by avvertix** [comment]
Turns out it was a bug as the item was selected using jQuery and the function to scroll was not defined at jQuery level
