### ISSUE TITLE
[Enhancement] Increase the list of characters considered as separators + search substrings

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#58]
### Short Description of the issue

One user was looking for the following document: 2017-05-20_UnifiedFramework_AllSubproducts_en.docx

All he knew is that the title contains "Unified Framework"

As a non tech-savvy, his first guess is to search for _unified framework_. Because of the underscores and because there is no separator between both words, the document is not found and he thus has to search for _\*unifiedframework\*_ (with stars and without space between the words), which is not intuitiuve for most "normal" users

### Expected behavior

The search engine should more strongly independent from the naming convention used in the K-Box.

1) The underscores should be recognized as separators (because most users use underscores and dashes without distinction)
2) The search engine should also be able to search substrings. In the example above, it should recognized that "unified" and "framework" are substrings of the title of this document

### General information

Version of your K-Box: 0.20

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
Hi @shenriod thanks for reporting the suggestion. We already improved the search component to better handling the filename punctuation and the ranking of search results. The described changes are available in [K-Search 3.2.0-1 release](https://github.com/k-box/k-search/releases/tag/v3.2.0-1)

**Comment by shenriod** [comment]
Confirmation that the example in this issue is correctly handled by K-Search 3.2.0:

Searching for _unified framework_ returns the document and so does _unified_
