### ISSUE TITLE
Remove useless blank character between the name of the institution and the closing ')' on the document panel

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#59]
### Short Description of the issue

![capture](https://user-images.githubusercontent.com/23653367/37201534-c885ada2-23a9-11e8-9957-59f13c8ae6eb.PNG)

### Expected behavior

N/A

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.20

URL of the page where the problem has occured:

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

_add here any relevant screenshots, screencasts, etc_

**Comment by avvertix** [comment]
This is not a presentation issue. The value used there comes from the Organization field in the User Profile. Apparently is present a space at the end of the Organization name field value.
