### ISSUE TITLE
Add multilingual support for the microsites

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#6]
For now, only English and Russian are supported for the content of the microsites

https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/microsites.php#L32
https://github.com/k-box/k-box/blob/3660407a6c018f05531843588602b3c7fc859567/resources/lang/en/microsites.php#L80-L81

At some point, add the possibility for other languages as well

**Comment by avvertix** [comment]
As part of #289 microsites are now disabled by default and moved behind a feature flag. This will start with version 0.29. Microsites might be deprecated in a future version as the adoption was very low
