### ISSUE TITLE
Make it easer to copy the link to a document

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#73]
### Short Description of the issue

Currently it requires at least 3 clicks to be able to copy the link to a document:

1) Click on the document
2) Click on "Sharing settings" (some users need to scroll down to access this button)
3) Click on Copy Link

Experience with (some) users has shown that this is not intuitive

### Expected behavior

The button "Copy link" should be accessible from different places. For example:

- In the contextual menu, when the user right-clicks on a document
- Beside [Preview | Download | Edit | Versions] in the document's panel
- Directly beside the document's name in the list of documents:

![capture](https://user-images.githubusercontent.com/23653367/39569556-fb68730c-4ede-11e8-80f2-f0582aad7d1c.PNG)

### Steps to reproduce the incorrect behavior
N/A

### General information

Version of your K-Box: 0.20.1

**Comment by avvertix** [comment]
Looking at the suggestions I think that the right click menu and the document's panel are possible locations. In addition to those I would also put it in the edit page. I don't think polluting the document list with another icon/button will be a good option.

**Comment by avvertix** [comment]
This is currently in progress. The current proposed solution is a "copy link" button on the document detail panel and in the details sidebar in the preview. In addition the same "copy link" button is available in the edit page.

![image](https://user-images.githubusercontent.com/5672748/100551926-230c1b80-3284-11eb-8cf2-75057b3bfac3.png)
