### ISSUE TITLE
[Improvement] Link to the download page of a document

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#74]
### Short Description of the issue

Currently the button "Copy link" points to the Preview page of the document. This is fine for the file types for which the preview is well supported (pdf, images) but not so nice for the types where the preview is not well supported (docx, doc, etc.)

### Expected behavior

By default, the link under "Copy link" should point to https://eba.klink.asia/klink/xxxxxxxxx/**download** if the document's type is not well supported. This will give a much nicer user experience

NB: this workaround might not be necessary if this issue is solved: https://github.com/k-box/k-box/issues/63

### Steps to reproduce the incorrect behavior

N/A
### General information

Version of your K-Box: 0.20.1

**Comment by avvertix** [comment]
I think that a change like that will not improve the user experience. It will create a discrepancy between links copied on the same K-Box version and between different K-Boxes (based on the version).

The preview page is the target for all links. This was done to make sure that users will experience the same type of interaction across different versions of the K-Box. Changing this behavior will have a big impact on users that are used to get the link to the preview page, disrupting their workflow. The current behavior is also adopter by other popular alternatives to the K-Box.

**Comment by avvertix** [comment]
There is a balance to keep between overall user experience, experience of a single feature and slowly changing the behavior of a feature used by the users. The link is a pretty simple feature, but your proposed change will have an immediate impact. Users fear changes, therefore a change needs to be accomodate in subsequent small changes to not have deep emotional reactions. The preview can be improved over time, while the link can be _download_ or _preview_ with no in-between possibilities.

**Comment by shenriod** [comment]
200% agreed! My proposal here was only meant as a temporary workaround. So if we can foresee a "good enough" improvement of the preview capacities of the most common poorly supported file types (docx, pptx, doc, ppt) in a relative short timeframe, I am more than happy to drop this issue!
