### ISSUE TITLE
Moving collections create url files instead (MS Edge)

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#81]
### Short Description of the issue

Moving documents in the K-Box is quite uncomfortable when using Microsoft Edge:

1) When dragging a document to a collection, the "icon" of the document is hiding the collection tree, making it difficult to see where the document will land
![img_20180516_142117](https://user-images.githubusercontent.com/23653367/40108708-29356ae8-5915-11e8-9999-7a4f203dd2d9.jpg)

2) Moving a (sub-) collection into another collection does not work. Instead, a "url" document is created:
![capture](https://user-images.githubusercontent.com/23653367/40108569-c153670e-5914-11e8-9e2c-0ba863715faf.PNG)

### Expected behavior

N/A

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.20.1

URL of the page where the problem has occured:

Type and version of your browser: Microsoft Edge 41.16299.248.0

In what language are you using your K-Box? 

### Screenshots

N/A

**Comment by avvertix** [comment]
Hi @shenriod we are aware of the second problem you mentioned. For better organizing I will update the title of the issue and divide the two points you mentioned in separate issues, as the cause is not related
