### ISSUE TITLE
Wrong counting of users who have access to a document

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#9]
When there is public link to a document, the sharing window no longer correctly counts the number of users who have access:

![capture](https://user-images.githubusercontent.com/23653367/35111359-5f18214c-fc7b-11e7-86f7-01bd00a670f6.PNG)

**Comment by avvertix** [comment]
In #412 we are refactoring the dialog window and the counter is not visible, but just the list.

**Comment by avvertix** [comment]
Closed because of changes in https://github.com/k-box/k-box/pull/412
